from isaacgymenvs.primitives.primitive_types import *
from isaacgymenvs.primitives.primitive_controllers import *

raise DeprecationWarning

primitive_seqs = (
    (
        "push_pivot",
        [
            PrimitivePlan(
                start_pose_WB=[
                    0.1218,
                    -0.1840,
                    1.0634,
                    -0.4145,
                    -0.5782,
                    -0.4103,
                    0.5706,
                ],
                goal_pose_WB=[
                    0.2582,
                    -0.1889,
                    1.0635,
                    -0.4145,
                    -0.5782,
                    -0.4103,
                    0.5706,
                ],
                primitive_type=PrimitiveType.Push,
                controller=None,
                max_num_steps=150,
                control_type="joint_imp",
            ),
            PrimitivePlan(
                start_pose_WB=None,
                goal_pose_WB=None,
                primitive_type=PrimitiveType.Pivot,
                controller=PivotController(
                    X_WE_start=np.eye(4), p_WC=np.zeros(3), action_steps=50
                ),
                max_num_steps=70,
                control_type="osc",
            ),
        ],
    ),
    (
        "push_push",
        [
            PrimitivePlan(
                start_pose_WB=[
                    0.0718,
                    -0.1840,
                    1.0634,
                    -0.4145,
                    -0.5782,
                    -0.4103,
                    0.5706,
                ],
                goal_pose_WB=[
                    0.2582,
                    -0.1889,
                    1.0635,
                    0.5148,
                    0.4892,
                    0.5006,
                    -0.4950,
                ],
                primitive_type=PrimitiveType.Push,
                controller=None,
                max_num_steps=150,
                control_type="joint_imp",
            ),
            PrimitivePlan(
                start_pose_WB=[
                    0.0718,
                    -0.1840,
                    1.0634,
                    -0.4145,
                    -0.5782,
                    -0.4103,
                    0.5706,
                ],
                goal_pose_WB=[
                    0.2582,
                    -0.3889,
                    1.0635,
                    0.5148,
                    0.4892,
                    0.5006,
                    -0.4950,
                ],
                primitive_type=PrimitiveType.Push,
                controller=None,
                max_num_steps=150,
                control_type="joint_imp",
            ),
        ],
    ),
)
